version: "3.7"
services:
  searcher:
    image: searcher
    container_name: searcher_api
    build: .
    restart: unless-stopped
    command: ['sh', '-c', 'uwsgi --yaml searcher/uwsgi.yml --py-autoreload 1']
    volumes:
      - "./searcher:/home/alpine/searcher:rw"
    env_file:
      - .ci/local.env
    networks:
      - searcher-network
    ports:
      - 6001:5000
  sphinx:
    image: stefobark/sphinxdocker
    container_name: sphinx_search
    restart: unless-stopped
    volumes:
      - "./dicts:/etc/sphinxsearch/dicts"
      - "./sphinx.conf:/etc/sphinxsearch/sphinx.conf"
networks:
  searcher-network:
